<a href="https://colab.research.google.com/github/lucas-estanislau/pe-de-meia/blob/main/pe_de_meia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pé-de-Meia**
### e sua relação com a permanência e o desempenho escolar no ensino médio no Brasil

In [1]:
import pandas as pd
import numpy as np
import requests
import zipfile
from io import BytesIO

In [2]:
# Função para carregar os dados zipados de cada mês do programa dentro do Portal da Transparência

def carregar_mes(url):
    response = requests.get(url, timeout=120)
    response.raise_for_status()

    with zipfile.ZipFile(BytesIO(response.content)) as zip_ref:
        arquivo = zip_ref.namelist()[0]

        with zip_ref.open(arquivo) as csv:
            df = pd.read_csv(csv, sep=";", encoding="latin1")

    return df

In [3]:
# Coletando dados dos beneficiários de 2024

mar24 = "https://portaldatransparencia.gov.br/download-de-dados/pe-de-meia/202403"
abr24 = "https://portaldatransparencia.gov.br/download-de-dados/pe-de-meia/202404"
mai24 = "https://portaldatransparencia.gov.br/download-de-dados/pe-de-meia/202405"
jun24 = "https://portaldatransparencia.gov.br/download-de-dados/pe-de-meia/202406"
ago24 = "https://portaldatransparencia.gov.br/download-de-dados/pe-de-meia/202408"
set24 = "https://portaldatransparencia.gov.br/download-de-dados/pe-de-meia/202409"
out24 = "https://portaldatransparencia.gov.br/download-de-dados/pe-de-meia/202410"
nov24 = "https://portaldatransparencia.gov.br/download-de-dados/pe-de-meia/202411"
dez24 = "https://portaldatransparencia.gov.br/download-de-dados/pe-de-meia/202412"

df_mar24 = carregar_mes(mar24)
df_abr24 = carregar_mes(abr24)
df_mai24 = carregar_mes(mai24)
df_jun24 = carregar_mes(jun24)
df_ago24 = carregar_mes(ago24)
df_set24 = carregar_mes(set24)
df_out24 = carregar_mes(out24)
df_nov24 = carregar_mes(nov24)
df_dez24 = carregar_mes(dez24)

/tmp/ipykernel_30926/1781375970.py:11: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv, sep=";", encoding="latin1")
/tmp/ipykernel_30926/1781375970.py:11: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv, sep=";", encoding="latin1")
/tmp/ipykernel_30926/1781375970.py:11: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv, sep=";", encoding="latin1")
/tmp/ipykernel_30926/1781375970.py:11: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv, sep=";", encoding="latin1")
/tmp/ipykernel_30926/1781375970.py:11: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv, sep=";", encoding="latin1")
/tmp/ipykernel_30926/1781375970.py:11: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv, sep=";", encoding="latin1")
/tmp/ipykernel_30926/1781375970.py:11: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv, sep=";", encoding="latin1")
/tmp/ipykernel_30926/1781375970.py:11: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv, sep=";", encoding="latin1")
/tmp/ipykernel_30926/1781375970.py:11: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv, sep=";", encoding="latin1")

In [4]:
print(f"MAR 24 - {df_mar24.shape[0]} COLUNAS")
print(f"ABR 24 - {df_abr24.shape[0]} COLUNAS")
print(f"JUN 24 - {df_jun24.shape[0]} COLUNAS")
print(f"AGO 24 - {df_ago24.shape[0]} COLUNAS")
print(f"SET 24 - {df_set24.shape[0]} COLUNAS")
print(f"OUT 24 - {df_out24.shape[0]} COLUNAS")
print(f"NOV 24 - {df_nov24.shape[0]} COLUNAS")
print(f"DEZ 24 - {df_dez24.shape[0]} COLUNAS")

MAR 24 - 2416252 COLUNAS
ABR 24 - 2762805 COLUNAS
JUN 24 - 3295860 COLUNAS
AGO 24 - 3152138 COLUNAS
SET 24 - 3282437 COLUNAS
OUT 24 - 3418224 COLUNAS
NOV 24 - 3404749 COLUNAS
DEZ 24 - 3412623 COLUNAS

In [5]:
df_mar24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2416252 entries, 0 to 2416251
Data columns (total 18 columns):
 #   Column                  Dtype
---  ------                  -----
 0   MÊS FOLHA               int64
 1   MÊS REFERÊNCIA          int64
 2   UF                      object
 3   CÓDIGO MUNICÍPIO SIAFI  int64
 4   NOME MUNICÍPIO          object
 5   NIS BENEFICIÁRIO        float64
 6   CPF BENEFICIÁRIO        object
 7   NOME BENEFICIÁRIO       object
 8   NIS RESPONSÁVEL         float64
 9   CPF RESPONSÁVEL         object
 10  NOME RESPONSÁVEL        object
 11  CÓDIGO TIPO INCENTIVO   int64
 12  TIPO INCENTIVO          object
 13  PERÍODO INCENTIVO       object
 14  CÓDIGO ETAPA ENSINO     int64
 15  ETAPA ENSINO            object
 16  DATA DO PAGAMENTO       object
 17  VALOR PARCELA           object
dtypes: float64(2), int64(5), object(11)
memory usage: 331.8+ MB

In [6]:
df_mar24.head()

,MÊS FOLHA,MÊS REFERÊNCIA,UF,CÓDIGO MUNICÍPIO SIAFI,NOME MUNICÍPIO,NIS BENEFICIÁRIO,CPF BENEFICIÁRIO,NOME BENEFICIÁRIO,NIS RESPONSÁVEL,CPF RESPONSÁVEL,NOME RESPONSÁVEL,CÓDIGO TIPO INCENTIVO,TIPO INCENTIVO,PERÍODO INCENTIVO,CÓDIGO ETAPA ENSINO,ETAPA ENSINO,DATA DO PAGAMENTO,VALOR PARCELA
0,202403,202403,AC,643,ACRELANDIA,2.126185e+10,***.408.142-**,ALLAN JHONATA DA SILVA HERMOGENES,1.624864e+10,***.338.912-**,IRACILDA HERMOGENES DE SOUZA FERREIRA,1,Matrícula,Ano letivo 2024,27,3º ano - Ensino Médio Regular,26/03/2024,"200,00"
1,202403,202403,AC,643,ACRELANDIA,2.120773e+10,***.655.722-**,BIANCA DA SILVA RIBEIRO,1.609672e+10,***.872.892-**,ANTONIA ROSEMIRA SANTOS DA SILVA,1,Matrícula,Ano letivo 2024,27,3º ano - Ensino Médio Regular,02/04/2024,"200,00"
2,202403,202403,AC,643,ACRELANDIA,2.380363e+10,***.379.332-**,DAYANE CARVALHO DA SILVA,2.102097e+10,***.323.582-**,ANGELA MARIA CARVALHO,1,Matrícula,Ano letivo 2024,27,3º ano - Ensino Médio Regular,03/04/2024,"200,00"
3,202403,202403,AC,643,ACRELANDIA,2.122791e+10,***.703.662-**,DEBORA DANTAS DE LIMA,2.122791e+10,***.703.662-**,DEBORA DANTAS DE LIMA,1,Matrícula,Ano letivo 2024,25,1º ano - Ensino Médio Regular,03/04/2024,"200,00"
4,202403,202403,AC,643,ACRELANDIA,2.362701e+10,***.319.892-**,DENNIS BOONE DE CARVALHO,2.093918e+10,***.434.512-**,NELSI BOONE,1,Matrícula,Ano letivo 2024,45,EJA - Educação de Jovens e Adultos,28/03/2024,"200,00"

In [7]:
dfs_2024 = [
    df_mar24,
    df_abr24,
    df_mai24,
    df_jun24,
    df_ago24,
    df_set24,
    df_out24,
    df_nov24,
    df_dez24
]

def converter_valor(df):
    df['VALOR PARCELA'] = (
        df['VALOR PARCELA'].str.replace(",", ".", regex=False).astype(float)
    )
    return df

for df in dfs_2024:
    converter_valor(df)

In [11]:
# Concatenando todos os meses de 2024
df_mar24_uf = df_mar24.groupby('UF')['VALOR PARCELA'].sum().reset_index().sort_values('VALOR PARCELA', ascending=False)
mar24

    UF  VALOR PARCELA
25  SP     65672000.0
4   BA     52117600.0
5   CE     41204800.0
10  MG     39749400.0
15  PE     35379400.0
13  PA     34366000.0
18  RJ     32183000.0
9   MA     29380600.0
2   AM     15417400.0
17  PR     14633200.0
1   AL     13298600.0
14  PB     13232000.0
22  RS     12721600.0
8   GO     12298400.0
19  RN     12070400.0
16  PI      9448400.0
24  SE      8014000.0
12  MT      7411600.0
7   ES      6616800.0
23  SC      6131200.0
6   DF      5397000.0
26  TO      4053600.0
11  MS      3838000.0
20  RO      3376000.0
3   AP      2969800.0
0   AC      1285000.0
21  RR       984600.0

In [13]:
df_mar24_uf.to_csv(
    "/content/drive/MyDrive/pe-de-meia/pe-de-meia-data/2024/mar24_uf.csv",
    index=False
)